name = "kinokawa-string-theme"
license = "MIT"
licenselink = "https://github.com/kinokawa-string/kinokawa-string-theme/LICENSE"
description = "A Hugo Theme for simple bloggable websites based on Kross."
homepage = "https://github.com/kinokawa-string/kinokawa-string-theme/"
demosite = "https://kinokawa-string.github.io/kinokawa-string-theme/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography', 'gethugothemes']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "Amadeus_vn"
  homepage = "https://amas.dev/"

[original]
  name = "kross"
  homepage = "https://themefisher.com/products/kross-creative-portfolio-template/"
